# Generated by Django 5.2.7 on 2025-11-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_stripe_price_id_course_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление курса"
            ),
        ),
    ]
