# Generated by Django 5.2.7 on 2025-12-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
        ("materials", "0005_course_last_update_at"),
    ]

    operations = []
